[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "development"

[functions]
  directory = "dist/netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["ethers", "@elizaos/core", "node-cron", "winston"]

[functions."governance-agent"]
  timeout = 30

[functions."scheduled-voting"]
  timeout = 25

[functions."scheduled-voting"]
  schedule = "*/5 * * * *"

[[redirects]]
  from = "/api/status"
  to = "/.netlify/functions/governance-agent/status"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/governance-agent/health"
  status = 200

[[redirects]]
  from = "/api/proposals"
  to = "/.netlify/functions/governance-agent/proposals"
  status = 200

[[redirects]]
  from = "/api/voting-history"
  to = "/.netlify/functions/governance-agent/voting-history"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/governance-agent/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.deploy-preview.environment]
  NODE_ENV = "development"
  ELIZA_RUNTIME = "development"

[context.branch-deploy.environment]
  NODE_ENV = "development"
  ELIZA_RUNTIME = "development"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://sepolia.infura.io https://api.coingecko.com wss://sepolia.infura.io; font-src 'self' data:;"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,HEAD,POST,OPTIONS"
    Access-Control-Allow-Headers = "Content-Type,Authorization"

# Environment variable templates (will be overridden by actual secrets)
[template.environment]
  OPENAI_API_KEY = "sk-your-openai-api-key-here"
  ETHEREUM_RPC_URL = "https://sepolia.infura.io/v3/ca485bd6567e4c5fb5693ee66a5885d8"  
  ETHERSCAN_API_KEY = "HG7DAYXKN5B6AZE35WRDVQRSNN5IDC3ZG6"
  AI_NODE_1_PRIVATE_KEY = "0xd74ae2c1a798042c9bbf56f15d2649df6d114e763f9444e2cddcde050900f1d0"
  AI_NODE_2_PRIVATE_KEY = "0x241083ae625b93b41b555052840c09458c71704889b22774101d21b4d1482e62"
  AI_NODE_3_PRIVATE_KEY = "0x0aa4b2f50b7efc44721b23a2ef7fc3ab11b658369af23381752c6d86b42628b1"
  AI_NODE_4_PRIVATE_KEY = "0x7dde37bea0f47ea849c9a7a285f3a277acd81c908accdb501ca036db1a5b11da"
  AI_NODE_5_PRIVATE_KEY = "0x64da71a2688d24c0f970ded84d2d744081e467ae493f4c3256c4f8ee9bb959ee"
  ADMIN_PRIVATE_KEY = "0xd74ae2c1a798042c9bbf56f15d2649df6d114e763f9444e2cddcde050900f1d0"
  ASSET_DAO_CONTRACT_ADDRESS = "0xa87e662061237a121Ca2E83E77dA8C251bc4B3529"
  AI_NODE_REGISTRY_ADDRESS = "0x0045c7D99489f1d8A5900243956B0206344417DD"
  DLOOP_TOKEN_ADDRESS = "0x05B366778566e93abfB8e4A9B794e4ad006446b4"
  SOULBOUND_NFT_ADDRESS = "0x6391C14631b2Be5374297fA3110687b80233104c"
  LOG_LEVEL = "info" 